---
version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
    commit-message:
      prefix: "build:"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
    commit-message:
      prefix: "chore:"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
    commit-message:
      prefix: "build(deps):"
      prefix-development: "chore(deps):"
    groups:
      eslint:
        patterns:
          - eslint
          - "@eslint/js"
    ignore:
      # @types/node has the type definitions for our current version of
      # Node.js, so we want to handle major version updates manually.
      # https://nodejs.org/en/about/previous-releases
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
    versioning-strategy: increase
