---
name: Handle new pull request
"on": pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  labeller:
    name: Pull request labeller
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request
        uses: actions/labeler@v6
        with:
          sync-labels: true

  dependabot:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    if:
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'infinityworks/govuk-frontend-starter'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          # PAT triggers workflows; GITHUB_TOKEN doesn't
          GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Approve a PR
        if: |
          steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
