---
name: Pre-merge checks

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Conventional pull request
        uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commitTitleMatch: false
          ignoreCommits: true

  run-code-quality-checks:
    uses: ./.github/workflows/code-quality-checks.yml
