---
name: Pre-merge checks

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Conventional pull request
        uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # if the PR contains a single commit, fail if the commit message and
          # the PR title do not match
          commitTitleMatch: false # default: true
          # if you squash merge PRs and enabled "Default to PR title for squash
          # merge commits", you can disable all linting of commits
          ignoreCommits: true # default: false
        with:
          commitlintRulesPath: "./commitlint.rules.js"

  run-code-quality-checks:
    name: Run code quality checks
    uses: ./.github/workflows/code-quality-checks.yml
