---
name: Handle push to `main`

"on":
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  code-quality:
    name: Verify code quality
    uses: ./.github/workflows/code-quality-checks.yml
